apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: session-broker

bases:
  - ../../base

patches:
  - path: patch-deployment.yaml
    target:
      kind: Deployment
      name: session-broker

images:
  - name: ghcr.io/jdarguello/session-broker
    newTag: "1.0.0"  # pin to a specific release tag in production
