apiVersion: apps/v1
kind: Deployment
metadata:
  name: session-broker
  namespace: session-broker
spec:
  replicas: 3
  template:
    spec:
      containers:
        - name: session-broker
          env:
            - name: APP_ENV
              value: "production"
          resources:
            requests:
              cpu: "200m"
              memory: "256Mi"
            limits:
              cpu: "1000m"
              memory: "512Mi"
