apiVersion: v1
kind: Service
metadata:
  name: session-broker
  namespace: session-broker
  labels:
    app: session-broker
spec:
  selector:
    app: session-broker
  ports:
    - name: http
      port: 80
      targetPort: 8000
  type: ClusterIP
